### ISSUE TITLE
Reloading models in the GUI does not reload imported libraries

### ISSUE THREAD

**Issue by hoogerheide** [reflectometry/refl1d#129]
Consider the following case:
1. A model file imports a library
2. The library is changed
3. The model is reloaded.

Ideally, the behavior of the updated model would reflect changes to the imported library, i.e. all imported libraries would be reloaded upon model reload. This apparently does not currently happen.

**Comment by bmaranville** [comment]
Re-importing libraries is a non-standard python operation.  The python interpreter automatically caches modules on import.  

It would be hard, without recreating a new python environment for every problem load, to ensure the libraries are reloaded.  That would be a major re-architecting of the backend, as the problems are currently compiled into the same python interpreter as bumps on load.

If this is an issue for your particular model, I suggest using ```importlib.reload(nameOfModule)``` and handling it within the model itself, instead of just using ```import nameOfModule``` in your problem file.  This is not a recursive operation (if there are other imports in the module you are reloading, they will not be reloaded) and this is why we can't easily do this by just applying importlib.reload on your model.

**Comment by bmaranville** [comment]
You might be able to do this with multiprocessing, if the start_method is "spawn" (new interpreter).  If the pickled problem just has module names in it it's possible it will try to reimport them from the newly spawned interpreter and get the update version.  

There are many caveats with this approach (default start_method for multiprocessing is "fork" on linux, for instance), and I don't know if the pickling/unpickling will go as I describe above.

**Comment by hoogerheide** [comment]
> Re-importing libraries is a non-standard python operation. The python interpreter automatically caches modules on import.
> 
> It would be hard, without recreating a new python environment for every problem load, to ensure the libraries are reloaded. That would be a major re-architecting of the backend, as the problems are currently compiled into the same python interpreter as bumps on load.
> 
> If this is an issue for your particular model, I suggest using `importlib.reload(nameOfModule)` and handling it within the model itself, instead of just using `import nameOfModule` in your problem file. This is not a recursive operation (if there are other imports in the module you are reloading, they will not be reloaded) and this is why we can't easily do this by just applying importlib.reload on your model.

This works. Thanks for the suggestion!
